apiVersion: batch/v1
kind: CronJob
metadata:
  name: syzbot-scraper
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: syzbot-scraper
            image: syzbot-scraper:latest  # Replace with your registry path
            args:
            - "--release"
            - "upstream"  # Can be changed to lts-5.15 or lts-6.1
            volumeMounts:
            - name: output-volume
              mountPath: /app/output
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: output-volume
            persistentVolumeClaim:
              claimName: syzbot-output-pvc
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syzbot-output-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust based on your needs 